function c(a){throw a;}var h=void 0,i=true,l=null,n=false;function aa(){return function(a){return a}}function p(a){return function(){return this[a]}}function q(a){return function(){return a}}var r,t=this;function ba(a,b){var d=a.split("."),e=t;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)!d.length&&v(b)?e[f]=b:e=e[f]?e[f]:e[f]={}}function ca(){}
function w(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function v(a){return a!==h}function ea(a){return w(a)=="array"}function fa(a){var b=w(a);return b=="array"||b=="object"&&typeof a.length=="number"}function x(a){return typeof a=="string"}function ga(a){return w(a)=="function"}function ha(a){a=w(a);return a=="object"||a=="array"||a=="function"}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ka=0;
function la(a,b,d){return a.call.apply(a.bind,arguments)}function ma(a,b,d){var e=b||t;if(arguments.length>2){var f=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,f);return a.apply(e,b)}}else return function(){return a.apply(e,arguments)}}function na(a,b,d){na=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?la:ma;return na.apply(l,arguments)}var oa=Date.now||function(){return+new Date};
function z(a,b){function d(){}d.prototype=b.prototype;a.m=b.prototype;a.prototype=new d};function pa(a){if(!qa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(ra,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(sa,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(ta,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(va,"&quot;"));return a}var ra=/&/g,sa=/</g,ta=/>/g,va=/\"/g,qa=/[&<>\"]/,wa={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},xa={"'":"\\'"};
function ya(a){var m;a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),g=b,j=d+1,k;if(!(k=wa[e])){if(!(f>31&&f<127))if(e in xa)e=xa[e];else if(e in wa)m=xa[e]=wa[e],e=m;else{f=e;k=e.charCodeAt(0);if(k>31&&k<127)f=e;else{if(k<256){if(f="\\x",k<16||k>256)f+="0"}else f="\\u",k<4096&&(f+="0");f+=k.toString(16).toUpperCase()}e=xa[e]=f}k=e}g[j]=k}b.push('"');return b.join("")}}
function za(a,b){for(var d=0,e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var k=e[j]||"",m=f[j]||"",o=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var u=o.exec(k)||["","",""],y=s.exec(m)||["","",""];if(u[0].length==0&&y[0].length==0)break;d=Aa(u[1].length==0?0:parseInt(u[1],10),y[1].length==0?0:parseInt(y[1],10))||Aa(u[2].length==0,y[2].length==0)||Aa(u[2],y[2])}while(d==
0)}return d}function Aa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ba(a){for(var b=0,d=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=4294967296;return b};var Ca,Da,Ea,Fa,Ga,Ha,Ia,Ja=(Ia="ScriptEngine"in t&&t.ScriptEngine()=="JScript")?t.ScriptEngineMajorVersion()+"."+t.ScriptEngineMinorVersion()+"."+t.ScriptEngineBuildVersion():"0";function Ka(a,b){this.s=Ia?[]:"";a!=l&&this.append.apply(this,arguments)}Ka.prototype.set=function(a){this.clear();this.append(a)};Ia?(Ka.prototype.ya=0,Ka.prototype.append=function(a,b,d){b==l?this.s[this.ya++]=a:(this.s.push.apply(this.s,arguments),this.ya=this.s.length);return this}):Ka.prototype.append=function(a,b,d){this.s+=a;if(b!=l)for(var e=1;e<arguments.length;e++)this.s+=arguments[e];return this};Ka.prototype.clear=function(){Ia?this.ya=this.s.length=0:this.s=""};
Ka.prototype.toString=function(){if(Ia){var a=this.s.join("");this.clear();a&&this.append(a);return a}else return this.s};function A(a,b){this.x=v(a)?a:0;this.y=v(b)?b:0}A.prototype.D=function(){return new A(this.x,this.y)};A.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function La(a,b){return new A(a.x-b.x,a.y-b.y)};function B(a,b,d,e){this.top=a;this.right=b;this.bottom=d;this.left=e}B.prototype.D=function(){return new B(this.top,this.right,this.bottom,this.left)};B.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};B.prototype.contains=function(a){return!this||!a?n:a instanceof B?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};
B.prototype.expand=function(a,b,d,e){ha(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=b,this.bottom+=d,this.left-=e);return this};function Ma(a,b){var d;if(b.x>=a.left&&b.x<=a.right)d=b.y>=a.top&&b.y<=a.bottom?0:b.y<a.top?a.top-b.y:b.y-a.bottom;else if(b.y>=a.top&&b.y<=a.bottom)d=b.x<a.left?a.left-b.x:b.x-a.right;else{var e=new A(b.x<a.left?a.left:a.right,b.y<a.top?a.top:a.bottom);d=b.x-e.x;e=b.y-e.y;d=Math.sqrt(d*d+e*e)}return d};var Na=Array.prototype,Oa=Na.indexOf?function(a,b,d){return Na.indexOf.call(a,b,d)}:function(a,b,d){d=d==l?0:d<0?Math.max(0,a.length+d):d;if(x(a))return!x(b)||b.length!=1?-1:a.indexOf(b,d);for(;d<a.length;d++)if(d in a&&a[d]===b)return d;return-1},Pa=Na.forEach?function(a,b,d){Na.forEach.call(a,b,d)}:function(a,b,d){for(var e=a.length,f=x(a)?a.split(""):a,g=0;g<e;g++)g in f&&b.call(d,f[g],g,a)};function Qa(a){return Na.concat.apply(Na,arguments)}
function Ra(a){if(ea(a))return Qa(a);else{for(var b=[],d=0,e=a.length;d<e;d++)b[d]=a[d];return b}}function Sa(a,b,d){return arguments.length<=2?Na.slice.call(a,b):Na.slice.call(a,b,d)};function Ta(){return t.navigator?t.navigator.userAgent:l}function Va(){return t.navigator}Ga=Fa=Ea=Da=Ca=n;var Wa;if(Wa=Ta()){var Xa=Va();Ca=Wa.indexOf("Opera")==0;Da=!Ca&&Wa.indexOf("MSIE")!=-1;Fa=(Ea=!Ca&&Wa.indexOf("WebKit")!=-1)&&Wa.indexOf("Mobile")!=-1;Ga=!Ca&&!Ea&&Xa.product=="Gecko"}var Ya=Ca,C=Da,Za=Ga,D=Ea,$a=Fa,ab=Va();Ha=(ab&&ab.platform||"").indexOf("Mac")!=-1;var bb=!!Va()&&(Va().appVersion||"").indexOf("X11")!=-1,cb;
a:{var db="",eb;if(Ya&&t.opera)var fb=t.opera.version,db=typeof fb=="function"?fb():fb;else if(Za?eb=/rv\:([^\);]+)(\)|;)/:C?eb=/MSIE\s+([^\);]+)(\)|;)/:D&&(eb=/WebKit\/(\S+)/),eb)var gb=eb.exec(Ta()),db=gb?gb[1]:"";if(C){var hb,ib=t.document;hb=ib?ib.documentMode:h;if(hb>parseFloat(db)){cb=String(hb);break a}}cb=db}var jb={};function E(a){return jb[a]||(jb[a]=za(cb,a)>=0)};var kb,lb=!C||E("9");!Za&&!C||C&&E("9")||Za&&E("1.9.1");C&&E("9");function mb(a,b){var d;d=(d=a.className)&&typeof d.split=="function"?d.split(/\s+/):[];var e=Sa(arguments,1),f;f=d;for(var g=0,j=0;j<e.length;j++)Oa(f,e[j])>=0||(f.push(e[j]),g++);f=g==e.length;a.className=d.join(" ");return f};function nb(a,b){this.width=a;this.height=b}nb.prototype.D=function(){return new nb(this.width,this.height)};nb.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};nb.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};nb.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function ob(a,b,d){for(var e in a)b.call(d,a[e],e,a)}function pb(a){var b=[],d=0,e;for(e in a)b[d++]=a[e];return b}function qb(a){var b={},d;for(d in a)b[d]=a[d];return b}var rb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function sb(a,b){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)a[d]=e[d];for(var g=0;g<rb.length;g++)d=rb[g],Object.prototype.hasOwnProperty.call(e,d)&&(a[d]=e[d])}};function tb(a){return a?new ub(F(a)):kb||(kb=new ub)}function vb(a){return x(a)?document.getElementById(a):a}function wb(a,b,d){return xb(a,b,d)}
function xb(a,b,d){d=d||document;a=a&&a!="*"?a.toUpperCase():"";if(d.querySelectorAll&&d.querySelector&&(!D||yb(document)||E("528"))&&(a||b))return d.querySelectorAll(a+(b?"."+b:""));if(b&&d.getElementsByClassName)if(d=d.getElementsByClassName(b),a){for(var e={},f=0,g=0,j;j=d[g];g++)a==j.nodeName&&(e[f++]=j);e.length=f;return e}else return d;d=d.getElementsByTagName(a||"*");if(b){e={};for(g=f=0;j=d[g];g++)a=j.className,typeof a.split=="function"&&Oa(a.split(/\s+/),b)>=0&&(e[f++]=j);e.length=f;return e}else return d}
function zb(a,b){ob(b,function(b,e){e=="style"?a.style.cssText=b:e=="class"?a.className=b:e=="for"?a.htmlFor=b:e in Ab?a.setAttribute(Ab[e],b):a[e]=b})}var Ab={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};function Bb(a,b,d){return Cb(document,arguments)}
function Cb(a,b){var d=b[0],e=b[1];if(!lb&&e&&(e.name||e.type)){d=["<",d];e.name&&d.push(' name="',pa(e.name),'"');if(e.type){d.push(' type="',pa(e.type),'"');var f={};sb(f,e);e=f;delete e.type}d.push(">");d=d.join("")}d=a.createElement(d);if(e)x(e)?d.className=e:ea(e)?mb.apply(l,[d].concat(e)):zb(d,e);b.length>2&&Db(a,d,b,2);return d}
function Db(a,b,d,e){function f(d){d&&b.appendChild(x(d)?a.createTextNode(d):d)}for(;e<d.length;e++){var g=d[e];fa(g)&&!(ha(g)&&g.nodeType>0)?Pa(Eb(g)?Ra(g):g,f):f(g)}}function yb(a){return a.compatMode=="CSS1Compat"}function Fb(a,b){a.appendChild(b)}function Gb(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function F(a){return a.nodeType==9?a:a.ownerDocument||a.document}function Eb(a){if(a&&typeof a.length=="number")if(ha(a))return typeof a.item=="function"||typeof a.item=="string";else if(ga(a))return typeof a.item=="function";return n}function ub(a){this.e=a||t.document||document}r=ub.prototype;r.pa=tb;r.g=function(a){return x(a)?this.e.getElementById(a):a};r.ob=function(a,b,d){return Cb(this.e,arguments)};r.createElement=function(a){return this.e.createElement(a)};r.createTextNode=function(a){return this.e.createTextNode(a)};
function Hb(a){var b=a.e,a=!D&&yb(b)?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return new A(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}r.appendChild=Fb;r.append=function(a,b){Db(F(a),a,arguments,1)};r.contains=Gb;function Ib(a,b,d,e){this.left=a;this.top=b;this.width=d;this.height=e}Ib.prototype.D=function(){return new Ib(this.left,this.top,this.width,this.height)};function Jb(a){return new B(a.top,a.left+a.width,a.top+a.height,a.left)}Ib.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
Ib.prototype.$a=function(a){var b=Math.max(this.left,a.left),d=Math.min(this.left+this.width,a.left+a.width);if(b<=d){var e=Math.max(this.top,a.top),a=Math.min(this.top+this.height,a.top+a.height);if(e<=a)return this.left=b,this.top=e,this.width=d-b,this.height=a-e,i}return n};
Ib.prototype.contains=function(a){return a instanceof Ib?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function Kb(a,b){var d=F(a);return d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,l))?d[b]||d.getPropertyValue(b):""}function Lb(a,b){return Kb(a,b)||(a.currentStyle?a.currentStyle[b]:l)||a.style[b]}function Mb(a){var a=a?a.nodeType==9?a:F(a):document,b;if(b=C)if(b=!E(9))b=tb(a),b=!yb(b.e);return b?a.body:a.documentElement}
function Pb(a){var b=a.getBoundingClientRect();if(C)a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop;return b}
function Qb(a){if(C)return a.offsetParent;for(var b=F(a),d=Lb(a,"position"),e=d=="fixed"||d=="absolute",a=a.parentNode;a&&a!=b;a=a.parentNode)if(d=Lb(a,"position"),e=e&&d=="static"&&a!=b.documentElement&&a!=b.body,!e&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||d=="fixed"||d=="absolute"))return a;return l}
function Rb(a){for(var b=new B(0,Infinity,Infinity,0),d=tb(a),e=d.e.body,f=!D&&yb(d.e)?d.e.documentElement:d.e.body,g;a=Qb(a);)if((!C||a.clientWidth!=0)&&(!D||a.clientHeight!=0||a!=e)&&(a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&Lb(a,"overflow")!="visible"){var j=Sb(a),k;k=a;if(Za&&!E("1.9")){var m=parseFloat(Kb(k,"borderLeftWidth"));if(Tb(k)){var o=k.offsetWidth-k.clientWidth-m-parseFloat(Kb(k,"borderRightWidth"));m+=o}k=new A(m,parseFloat(Kb(k,"borderTopWidth")))}else k=new A(k.clientLeft,
k.clientTop);j.x+=k.x;j.y+=k.y;b.top=Math.max(b.top,j.y);b.right=Math.min(b.right,j.x+a.clientWidth);b.bottom=Math.min(b.bottom,j.y+a.clientHeight);b.left=Math.max(b.left,j.x);g=g||a!=f}e=f.scrollLeft;f=f.scrollTop;D?(b.left+=e,b.top+=f):(b.left=Math.max(b.left,e),b.top=Math.max(b.top,f));if(!g||D)b.right+=e,b.bottom+=f;d=d.e.parentWindow||d.e.defaultView||window;g=d.document;D&&!E("500")&&!$a?(typeof d.innerHeight=="undefined"&&(d=window),g=d.innerHeight,a=d.document.documentElement.scrollHeight,
d==d.top&&a<g&&(g-=15),d=new nb(d.innerWidth,g)):(d=yb(g)?g.documentElement:g.body,d=new nb(d.clientWidth,d.clientHeight));b.right=Math.min(b.right,e+d.width);b.bottom=Math.min(b.bottom,f+d.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>b.left?b:l}
function Sb(a){var b,d=F(a),e=Lb(a,"position"),f=Za&&d.getBoxObjectFor&&!a.getBoundingClientRect&&e=="absolute"&&(b=d.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),g=new A(0,0),j=Mb(d);if(a==j)return g;if(a.getBoundingClientRect)b=Pb(a),a=Hb(tb(d)),g.x=b.left+a.x,g.y=b.top+a.y;else if(d.getBoxObjectFor&&!f)b=d.getBoxObjectFor(a),a=d.getBoxObjectFor(j),g.x=b.screenX-a.screenX,g.y=b.screenY-a.screenY;else{b=a;do{g.x+=b.offsetLeft;g.y+=b.offsetTop;b!=a&&(g.x+=b.clientLeft||0,g.y+=b.clientTop||0);if(D&&
Lb(b,"position")=="fixed"){g.x+=d.body.scrollLeft;g.y+=d.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ya||D&&e=="absolute")g.y-=d.body.offsetTop;for(b=a;(b=Qb(b))&&b!=d.body&&b!=j;)if(g.x-=b.scrollLeft,!Ya||b.tagName!="TR")g.y-=b.scrollTop}return g}function Ub(a,b){typeof a=="number"&&(a=(b?Math.round(a):a)+"px");return a}
function Vb(a){if(Lb(a,"display")!="none")return new nb(a.offsetWidth,a.offsetHeight);var b=a.style,d=b.display,e=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";var g=a.offsetWidth,a=a.offsetHeight;b.display=d;b.position=f;b.visibility=e;return new nb(g,a)}function Wb(a){var b=Sb(a),a=Vb(a);return new Ib(b.x,b.y,a.width,a.height)}function Xb(a,b){a.style.display=b?"":"none"}function Tb(a){return"rtl"==Lb(a,"direction")};function Yb(a,b,d,e,f,g,j,k){var m,o=d.offsetParent;if(o){var s=o.tagName=="HTML"||o.tagName=="BODY";if(!s||Lb(o,"position")!="static")m=Sb(o),s||(m=La(m,new A(o.scrollLeft,o.scrollTop)))}o=Wb(a);(s=Rb(a))&&o.$a(new Ib(s.left,s.top,s.right-s.left,s.bottom-s.top));var s=tb(a),u=tb(d);if(s.e!=u.e){var y=s.e.body,u=u.e.parentWindow||u.e.defaultView,K=new A(0,0),Ua=F(y)?F(y).parentWindow||F(y).defaultView:window,Ec=y;do{var da;if(Ua==u)da=Sb(Ec);else{var G=Ec;da=new A;if(G.nodeType==1)if(G.getBoundingClientRect)G=
Pb(G),da.x=G.left,da.y=G.top;else{var Nb=Hb(tb(G)),G=Sb(G);da.x=G.x-Nb.x;da.y=G.y-Nb.y}else{var Nb=ga(G.rb),Ob=G;G.targetTouches?Ob=G.targetTouches[0]:Nb&&G.G.targetTouches&&(Ob=G.G.targetTouches[0]);da.x=Ob.clientX;da.y=Ob.clientY}}K.x+=da.x;K.y+=da.y}while(Ua&&Ua!=u&&(Ec=Ua.frameElement)&&(Ua=Ua.parent));y=La(K,Sb(y));C&&!yb(s.e)&&(y=La(y,Hb(s)));o.left+=y.x;o.top+=y.y}a=(b&4&&Tb(a)?b^2:b)&-5;b=new A(a&2?o.left+o.width:o.left,a&1?o.top+o.height:o.top);m&&(b=La(b,m));f&&(b.x+=(a&2?-1:1)*f.x,b.y+=
(a&1?-1:1)*f.y);var ua;if(j&&(ua=Rb(d))&&m)ua.top=Math.max(0,ua.top-m.y),ua.right-=m.x,ua.bottom-=m.y,ua.left=Math.max(0,ua.left-m.x);return Zb(b,d,e,g,ua,j,k)}
function Zb(a,b,d,e,f,g,j){var a=a.D(),k=0,m=(d&4&&Tb(b)?d^2:d)&-5,d=Vb(b),j=j?j.D():d;if(e||m!=0)m&2?a.x-=j.width+(e?e.right:0):e&&(a.x+=e.left),m&1?a.y-=j.height+(e?e.bottom:0):e&&(a.y+=e.top);if(g){if(f){k=a;e=0;if(k.x<f.left&&g&1)k.x=f.left,e|=1;k.x<f.left&&k.x+j.width>f.right&&g&16&&(j.width-=k.x+j.width-f.right,e|=4);if(k.x+j.width>f.right&&g&1)k.x=Math.max(f.right-j.width,f.left),e|=1;g&2&&(e|=(k.x<f.left?16:0)|(k.x+j.width>f.right?32:0));if(k.y<f.top&&g&4)k.y=f.top,e|=2;k.y>=f.top&&k.y+j.height>
f.bottom&&g&32&&(j.height-=k.y+j.height-f.bottom,e|=8);if(k.y+j.height>f.bottom&&g&4)k.y=Math.max(f.bottom-j.height,f.top),e|=2;g&8&&(e|=(k.y<f.top?64:0)|(k.y+j.height>f.bottom?128:0));k=e}else k=256;if(k&496)return k}g=a;f=Za&&(Ha||bb)&&E("1.9");g instanceof A?(a=g.x,g=g.y):(a=g,g=h);b.style.left=Ub(a,f);b.style.top=Ub(g,f);if(!(d==j||(!d||!j?0:d.width==j.width&&d.height==j.height))){var d=j,o;d instanceof nb?(o=d.height,d=d.width):c(Error("missing height argument"));b.style.width=Ub(d,i);b.style.height=
Ub(o,i)}return k};function $b(){}$b.prototype.r=function(){};function ac(a,b){this.element=a;this.Pa=b}z(ac,$b);ac.prototype.r=function(a,b,d){Yb(this.element,this.Pa,a,b,h,d)};var bc;function cc(){}cc.prototype.Ta=n;cc.prototype.ga=function(){if(!this.Ta)this.Ta=i,this.i()};cc.prototype.i=function(){};!C||E("9");var dc=C&&!E("8");function ec(a,b){this.type=a;this.currentTarget=this.target=b}z(ec,cc);r=ec.prototype;r.i=function(){delete this.type;delete this.target;delete this.currentTarget};r.Q=n;r.ma=i;r.stopPropagation=function(){this.Q=i};r.preventDefault=function(){this.ma=n};var fc=new Function("a","return a");function gc(a,b){a&&this.ra(a,b)}z(gc,ec);r=gc.prototype;r.target=l;r.relatedTarget=l;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=n;r.altKey=n;r.shiftKey=n;r.metaKey=n;r.vb=n;r.G=l;
r.ra=function(a,b){var d=this.type=a.type;ec.call(this,d);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(Za)try{fc(e.nodeName)}catch(f){e=l}}else if(d=="mouseover")e=a.fromElement;else if(d=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(d=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.vb=Ha?a.metaKey:a.ctrlKey;this.state=a.state;this.G=a;delete this.ma;delete this.Q};r.stopPropagation=function(){gc.m.stopPropagation.call(this);this.G.stopPropagation?this.G.stopPropagation():this.G.cancelBubble=i};
r.preventDefault=function(){gc.m.preventDefault.call(this);var a=this.G;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,dc)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};r.rb=p("G");r.i=function(){gc.m.i.call(this);this.relatedTarget=this.currentTarget=this.target=this.G=l};function hc(){}var ic=0;r=hc.prototype;r.key=0;r.Z=n;r.Na=n;r.ra=function(a,b,d,e,f,g){ga(a)?this.ab=i:a&&a.handleEvent&&ga(a.handleEvent)?this.ab=n:c(Error("Invalid listener argument"));this.ka=a;this.kb=b;this.src=d;this.type=e;this.capture=!!f;this.Ca=g;this.Na=n;this.key=++ic;this.Z=n};r.handleEvent=function(a){return this.ab?this.ka.call(this.Ca||this.src,a):this.ka.handleEvent.call(this.ka,a)};function H(a,b){this.cb=b;this.O=[];a>this.cb&&c(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<a;d++)this.O.push(this.F?this.F():{})}z(H,cc);H.prototype.F=l;H.prototype.Sa=l;function jc(a){return a.O.length?a.O.pop():a.F?a.F():{}}function kc(a,b){a.O.length<a.cb?a.O.push(b):lc(a,b)}function lc(a,b){if(a.Sa)a.Sa(b);else if(ha(b))if(ga(b.ga))b.ga();else for(var d in b)delete b[d]}
H.prototype.i=function(){H.m.i.call(this);for(var a=this.O;a.length;)lc(this,a.pop());delete this.O};var mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc;
(function(){function a(){return{h:0,q:0}}function b(){return[]}function d(){function a(b){return j.call(a.src,a.key,b)}return a}function e(){return new hc}function f(){return new gc}var g=Ia&&!(za(Ja,"5.7")>=0),j;rc=function(a){j=a};if(g){mc=function(){return jc(k)};nc=function(a){kc(k,a)};oc=function(){return jc(m)};pc=function(a){kc(m,a)};qc=function(){return jc(o)};sc=function(){kc(o,d())};tc=function(){return jc(s)};uc=function(a){kc(s,a)};vc=function(){return jc(u)};wc=function(a){kc(u,a)};var k=
new H(0,600);k.F=a;var m=new H(0,600);m.F=b;var o=new H(0,600);o.F=d;var s=new H(0,600);s.F=e;var u=new H(0,600);u.F=f}else mc=a,nc=ca,oc=b,pc=ca,qc=d,sc=ca,tc=e,uc=ca,vc=f,wc=ca})();var xc={},I={},yc={},zc={};
function J(a,b,d,e,f){if(b)if(ea(b)){for(var g=0;g<b.length;g++)J(a,b[g],d,e,f);return l}else{var e=!!e,j=I;b in j||(j[b]=mc());j=j[b];e in j||(j[e]=mc(),j.h++);var j=j[e],k=ia(a),m;j.q++;if(j[k]){m=j[k];for(g=0;g<m.length;g++)if(j=m[g],j.ka==d&&j.Ca==f){if(j.Z)break;return m[g].key}}else m=j[k]=oc(),j.h++;g=qc();g.src=a;j=tc();j.ra(d,g,a,b,e,f);d=j.key;g.key=d;m.push(j);xc[d]=j;yc[k]||(yc[k]=oc());yc[k].push(j);a.addEventListener?(a==t||!a.Ra)&&a.addEventListener(b,g,e):a.attachEvent(b in zc?zc[b]:
zc[b]="on"+b,g);return d}else c(Error("Invalid event type"))}function Ac(a,b,d,e,f){if(ea(b))for(var g=0;g<b.length;g++)Ac(a,b[g],d,e,f);else{e=!!e;a:{g=I;if(b in g&&(g=g[b],e in g&&(g=g[e],a=ia(a),g[a]))){a=g[a];break a}a=l}if(a)for(g=0;g<a.length;g++)if(a[g].ka==d&&a[g].capture==e&&a[g].Ca==f){Bc(a[g].key);break}}}
function Bc(a){if(xc[a]){var b=xc[a];if(!b.Z){var d=b.src,e=b.type,f=b.kb,g=b.capture;d.removeEventListener?(d==t||!d.Ra)&&d.removeEventListener(e,f,g):d.detachEvent&&d.detachEvent(e in zc?zc[e]:zc[e]="on"+e,f);d=ia(d);f=I[e][g][d];if(yc[d]){var j=yc[d],k=Oa(j,b);k>=0&&Na.splice.call(j,k,1);j.length==0&&delete yc[d]}b.Z=i;f.gb=i;Cc(e,g,d,f);delete xc[a]}}}
function Cc(a,b,d,e){if(!e.ta&&e.gb){for(var f=0,g=0;f<e.length;f++)if(e[f].Z){var j=e[f].kb;j.src=l;sc(j);uc(e[f])}else f!=g&&(e[g]=e[f]),g++;e.length=g;e.gb=n;g==0&&(pc(e),delete I[a][b][d],I[a][b].h--,I[a][b].h==0&&(nc(I[a][b]),delete I[a][b],I[a].h--),I[a].h==0&&(nc(I[a]),delete I[a]))}}
function Dc(a){var b,d=0,e=b==l;b=!!b;if(a==l)ob(yc,function(a){for(var f=a.length-1;f>=0;f--){var g=a[f];if(e||b==g.capture)Bc(g.key),d++}});else if(a=ia(a),yc[a])for(var a=yc[a],f=a.length-1;f>=0;f--){var g=a[f];if(e||b==g.capture)Bc(g.key),d++}}function Fc(a,b,d,e,f){var g=1,b=ia(b);if(a[b]){a.q--;a=a[b];a.ta?a.ta++:a.ta=1;try{for(var j=a.length,k=0;k<j;k++){var m=a[k];m&&!m.Z&&(g&=Gc(m,f)!==n)}}finally{a.ta--,Cc(d,e,b,a)}}return Boolean(g)}
function Gc(a,b){var d=a.handleEvent(b);a.Na&&Bc(a.key);return d}
rc(function(a,b){if(!xc[a])return i;var d=xc[a],e=d.type,f=I;if(!(e in f))return i;var f=f[e],g,j;bc===h&&(bc=C&&!t.addEventListener);if(bc){var k;if(!(k=b))a:{k="window.event".split(".");for(var m=t;g=k.shift();)if(m[g]!=l)m=m[g];else{k=l;break a}k=m}g=k;k=i in f;m=n in f;if(k){if(g.keyCode<0||g.returnValue!=h)return i;a:{var o=n;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(s){o=i}if(o||g.returnValue==h)g.returnValue=i}}o=vc();o.ra(g,this);g=i;try{if(k){for(var u=oc(),y=o.currentTarget;y;y=y.parentNode)u.push(y);
j=f[i];j.q=j.h;for(var K=u.length-1;!o.Q&&K>=0&&j.q;K--)o.currentTarget=u[K],g&=Fc(j,u[K],e,i,o);if(m){j=f[n];j.q=j.h;for(K=0;!o.Q&&K<u.length&&j.q;K++)o.currentTarget=u[K],g&=Fc(j,u[K],e,n,o)}}else g=Gc(d,o)}finally{if(u)u.length=0,pc(u);o.ga();wc(o)}return g}e=new gc(b,this);try{g=Gc(d,e)}finally{e.ga()}return g});function Hc(a){this.p=a}z(Hc,cc);var Ic=new H(0,100),Jc=[];function Kc(a,b,d,e,f){ea(d)||(Jc[0]=d,d=Jc);for(var g=0;g<d.length;g++){var j=a,k=J(b,d[g],e||a,f||n,a.p||a);j.c?j.c[k]=i:j.ja?(j.c=jc(Ic),j.c[j.ja]=i,j.ja=l,j.c[k]=i):j.ja=k}}Hc.prototype.Ja=function(){if(this.c){for(var a in this.c)Bc(a),delete this.c[a];kc(Ic,this.c);this.c=l}else this.ja&&Bc(this.ja)};Hc.prototype.i=function(){Hc.m.i.call(this);this.Ja()};Hc.prototype.handleEvent=function(){c(Error("EventHandler.handleEvent not implemented"))};function Lc(a,b){this.za=a instanceof A?a:new A(a,b)}z(Lc,$b);Lc.prototype.r=function(a,b,d,e){Yb(Mb(a),0,a,b,this.za,d,l,e)};function Mc(){}z(Mc,cc);r=Mc.prototype;r.Ra=i;r.Ga=l;r.addEventListener=function(a,b,d,e){J(this,a,b,d,e)};r.removeEventListener=function(a,b,d,e){Ac(this,a,b,d,e)};
r.dispatchEvent=function(a){var b=a.type||a,d=I;if(b in d){if(x(a))a=new ec(a,this);else if(a instanceof ec)a.target=a.target||this;else{var e=a,a=new ec(b,this);sb(a,e)}var e=1,f,d=d[b],b=i in d,g;if(b){f=[];for(g=this;g;g=g.Ga)f.push(g);g=d[i];g.q=g.h;for(var j=f.length-1;!a.Q&&j>=0&&g.q;j--)a.currentTarget=f[j],e&=Fc(g,f[j],a.type,i,a)&&a.ma!=n}if(n in d)if(g=d[n],g.q=g.h,b)for(j=0;!a.Q&&j<f.length&&g.q;j++)a.currentTarget=f[j],e&=Fc(g,f[j],a.type,n,a)&&a.ma!=n;else for(f=this;!a.Q&&f&&g.q;f=f.Ga)a.currentTarget=
f,e&=Fc(g,f,a.type,n,a)&&a.ma!=n;a=Boolean(e)}else a=i;return a};r.i=function(){Mc.m.i.call(this);Dc(this);this.Ga=l};var Nc=t.window;function Oc(a,b,d){ga(a)?d&&(a=na(a,d)):a&&typeof a.handleEvent=="function"?a=na(a.handleEvent,a):c(Error("Invalid listener argument"));return b>2147483647?-1:Nc.setTimeout(a,b||0)};function Pc(a,b){this.p=new Hc(this);this.Ka(a||l);if(b)this.ba=b}z(Pc,Mc);r=Pc.prototype;r.j=l;r.mb=i;r.Ma=l;r.k=n;r.xb=n;r.Da=-1;r.bb=-1;r.sb=n;r.qb=i;r.ba="toggle_display";r.g=p("j");r.Ka=function(a){this.k&&c(Error("Can not change this state of the popup while showing."));this.j=a};
function Qc(a,b){if(b){if(!a.k&&a.Ea()){a.j||c(Error("Caller must call setElement before trying to show the popup"));a.r();var d=F(a.j);a.sb&&Kc(a.p,d,"keydown",a.ub,i);if(a.mb)if(Kc(a.p,d,"mousedown",a.ib,i),C){for(var e=d.activeElement;e&&e.nodeName=="IFRAME";){try{var f=D?e.document||e.contentWindow.document:e.contentDocument||e.contentWindow.document}catch(g){break}d=f;e=d.activeElement}Kc(a.p,d,"mousedown",a.ib,i);Kc(a.p,d,"deactivate",a.hb)}else Kc(a.p,d,"blur",a.hb);a.ba=="toggle_display"?
(a.j.style.visibility="visible",Xb(a.j,i)):a.ba=="move_offscreen"&&a.r();a.k=i;a.Fa()}}else Rc(a)}r.r=ca;function Rc(a,b){if(!a.k||!a.dispatchEvent({type:"beforehide",target:b}))return n;a.p&&a.p.Ja();if(a.ba=="toggle_display")a.xb?Oc(a.Ya,0,a):a.Ya();else if(a.ba=="move_offscreen")a.j.style.left="-200px",a.j.style.top="-200px";a.k=n;a.la(b);return i}r.Ya=function(){this.j.style.visibility="hidden";Xb(this.j,n)};r.Ea=function(){return this.dispatchEvent("beforeshow")};
r.Fa=function(){this.Da=oa();this.bb=-1;this.dispatchEvent("show")};r.la=function(a){this.bb=oa();this.dispatchEvent({type:"hide",target:a})};r.ib=function(a){a=a.target;!Gb(this.j,a)&&(!this.Ma||Gb(this.Ma,a))&&!(oa()-this.Da<150)&&Rc(this,a)};r.ub=function(a){a.keyCode==27&&Rc(this,a.target)&&(a.preventDefault(),a.stopPropagation())};r.hb=function(a){if(this.qb){var b=F(this.j);if(C||Ya){if((a=b.activeElement)&&Gb(this.j,a))return}else if(a.target!=b)return;oa()-this.Da<150||Rc(this)}};
r.i=function(){Pc.m.i.call(this);this.p.ga();delete this.j;delete this.p};function Sc(a,b){this.wb=4;this.Ha=b||h;Pc.call(this,a)}z(Sc,Pc);function Tc(a){var b=new B(100,0,0,100);a.tb=b==l||b instanceof B?b:new B(b,h,h,h);a.k&&a.r()}Sc.prototype.r=function(){if(this.Ha){var a=!this.k&&this.ba!="move_offscreen",b=this.g();if(a)b.style.visibility="hidden",Xb(b,i);this.Ha.r(b,this.wb,this.tb);a&&Xb(b,n)}};function Uc(a){if(typeof a.W=="function")return a.W();if(x(a))return a.split("");if(fa(a)){for(var b=[],d=a.length,e=0;e<d;e++)b.push(a[e]);return b}return pb(a)};function Vc(a,b){this.l={};this.c=[];var d=arguments.length;if(d>1){d%2&&c(Error("Uneven number of arguments"));for(var e=0;e<d;e+=2)this.set(arguments[e],arguments[e+1])}else a&&this.wa(a)}r=Vc.prototype;r.h=0;r.La=0;r.W=function(){Wc(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.l[this.c[b]]);return a};r.clear=function(){this.l={};this.La=this.h=this.c.length=0};
r.remove=function(a){return Object.prototype.hasOwnProperty.call(this.l,a)?(delete this.l[a],this.h--,this.La++,this.c.length>2*this.h&&Wc(this),i):n};function Wc(a){if(a.h!=a.c.length){for(var b=0,d=0;b<a.c.length;){var e=a.c[b];Object.prototype.hasOwnProperty.call(a.l,e)&&(a.c[d++]=e);b++}a.c.length=d}if(a.h!=a.c.length){for(var f={},d=b=0;b<a.c.length;)e=a.c[b],Object.prototype.hasOwnProperty.call(f,e)||(a.c[d++]=e,f[e]=1),b++;a.c.length=d}}
r.set=function(a,b){Object.prototype.hasOwnProperty.call(this.l,a)||(this.h++,this.c.push(a),this.La++);this.l[a]=b};r.wa=function(a){var b;if(a instanceof Vc)Wc(a),b=a.c.concat(),a=a.W();else{b=[];var d=0,e;for(e in a)b[d++]=e;a=pb(a)}for(d=0;d<b.length;d++)this.set(b[d],a[d])};r.D=function(){return new Vc(this)};function Xc(a){this.l=new Vc;a&&this.wa(a)}function Yc(a){var b=typeof a;return b=="object"&&a||b=="function"?"o"+ia(a):b.substr(0,1)+a}r=Xc.prototype;r.add=function(a){this.l.set(Yc(a),a)};r.wa=function(a){for(var a=Uc(a),b=a.length,d=0;d<b;d++)this.add(a[d])};r.Ja=function(a){for(var a=Uc(a),b=a.length,d=0;d<b;d++)this.remove(a[d])};r.remove=function(a){return this.l.remove(Yc(a))};r.clear=function(){this.l.clear()};
r.contains=function(a){a=Yc(a);return Object.prototype.hasOwnProperty.call(this.l.l,a)};r.$a=function(a){for(var b=new Xc,a=Uc(a),d=0;d<a.length;d++){var e=a[d];this.contains(e)&&b.add(e)}return b};r.W=function(){return this.l.W()};r.D=function(){return new Xc(this)};function Zc(a,b,d){this.ha=d||(a?tb(vb(a)):tb());Sc.call(this,this.ha.ob("div",{style:"position:absolute;display:none;"}));this.M=new A(1,1);this.N=new Xc;a&&(a=vb(a),this.N.add(a),J(a,"mouseover",this.Va,n,this),J(a,"mouseout",this.qa,n,this),J(a,"mousemove",this.X,n,this),J(a,"focus",this.Ua,n,this),J(a,"blur",this.qa,n,this));if(b!=l)if(a=this.g(),"textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=
b}else{for(;d=a.firstChild;)a.removeChild(d);a.appendChild(F(a).createTextNode(b))}}z(Zc,Sc);var $c=[];r=Zc.prototype;r.f=l;r.className="goog-tooltip";r.lb=500;r.Xa=0;r.pa=p("ha");r.detach=function(a){if(a)a=vb(a),ad(this,a),this.N.remove(a);else{for(var b=this.N.W(),d=0;a=b[d];d++)ad(this,a);this.N.clear()}};function ad(a,b){Ac(b,"mouseover",a.Va,n,a);Ac(b,"mouseout",a.qa,n,a);Ac(b,"mousemove",a.X,n,a);Ac(b,"focus",a.Ua,n,a);Ac(b,"blur",a.qa,n,a)}r.Aa=p("Xa");function bd(a,b){a.g().innerHTML=b}
r.Ka=function(a){var b=this.g();b&&b&&b.parentNode&&b.parentNode.removeChild(b);Zc.m.Ka.call(this,a);if(a)b=this.ha.e.body,b.insertBefore(a,b.lastChild)};function cd(a){return a.K?a.k?4:1:a.Y?3:a.k?2:0}r.sa=function(a){if(!this.k)return n;var b=Sb(this.g()),d=Vb(this.g());return b.x<=a.x&&a.x<=b.x+d.width&&b.y<=a.y&&a.y<=b.y+d.height};
r.Ea=function(){if(!Pc.prototype.Ea.call(this))return n;if(this.anchor)for(var a,b=0;a=$c[b];b++)Gb(a.g(),this.anchor)||Qc(a,n);Oa($c,this)>=0||$c.push(this);a=this.g();a.className=this.className;dd(this);J(a,"mouseover",this.Ba,n,this);J(a,"mouseout",this.Wa,n,this);ed(this);return i};
r.la=function(){var a=Oa($c,this);a>=0&&Na.splice.call($c,a,1);for(var a=this.g(),b,d=0;b=$c[d];d++)b.anchor&&Gb(a,b.anchor)&&Qc(b,n);this.jb&&fd(this.jb);Ac(a,"mouseover",this.Ba,n,this);Ac(a,"mouseout",this.Wa,n,this);this.anchor=h;if(cd(this)==0)this.va=n;Pc.prototype.la.call(this)};
r.fb=function(a,b){if(this.anchor==a&&this.N.contains(this.anchor))if(this.va||!this.yb){if(Qc(this,n),!this.k){var d;b?d=b:(d=this.M.D(),d=new gd(d));this.anchor=a;this.Ha=d||h;this.k&&this.r();Qc(this,i)}}else this.anchor=h;this.K=h};r.eb=function(a){this.Y=h;a==this.anchor&&(this.f==l||this.f!=this.g()&&!this.N.contains(this.f))&&(!this.R||!this.R.f)&&Qc(this,n)};function hd(a,b){var d=Hb(a.ha);a.M.x=b.clientX+d.x;a.M.y=b.clientY+d.y}
r.Va=function(a){var b=id(this,a.target);this.f=b;dd(this);if(b!=this.anchor){this.anchor=b;if(!this.K)this.K=Oc(na(this.fb,this,b,h),this.lb);jd(this);hd(this,a)}};function id(a,b){try{for(;b&&!a.N.contains(b);)b=b.parentNode;return b}catch(d){return l}}r.X=function(a){hd(this,a);this.va=i};r.Ua=function(a){this.f=a=id(this,a.target);this.va=i;if(this.anchor!=a){this.anchor=a;var b=new kd(this.f);dd(this);if(!this.K)this.K=Oc(na(this.fb,this,a,b),this.lb);jd(this)}};
function jd(a){if(a.anchor)for(var b,d=0;b=$c[d];d++)if(Gb(b.g(),a.anchor))b.R=a,a.jb=b}r.qa=function(a){var b=id(this,a.target),d=id(this,a.relatedTarget);if(b!=d){if(b==this.f)this.f=l;ed(this);this.va=n;this.k&&(!a.relatedTarget||!Gb(this.g(),a.relatedTarget))?fd(this):this.anchor=h}};r.Ba=function(){var a=this.g();if(this.f!=a)dd(this),this.f=a};r.Wa=function(a){var b=this.g();if(this.f==b&&(!a.relatedTarget||!Gb(b,a.relatedTarget)))this.f=l,fd(this)};
function ed(a){if(a.K)Nc.clearTimeout(a.K),a.K=h}function fd(a){if(cd(a)==2)a.Y=Oc(na(a.eb,a,a.anchor),a.Aa())}function dd(a){if(a.Y)Nc.clearTimeout(a.Y),a.Y=h}r.i=function(){Qc(this,n);ed(this);this.detach();if(this.g()){var a=this.g();a&&a.parentNode&&a.parentNode.removeChild(a)}this.f=l;delete this.ha;Zc.m.i.call(this)};function gd(a,b){Lc.call(this,a,b)}z(gd,Lc);
gd.prototype.r=function(a,b,d){b=Mb(a);b=Rb(b);d=d?new B(d.top+10,d.right,d.bottom,d.left+10):new B(10,0,0,10);Zb(this.za,a,4,d,b,9)&496&&Zb(this.za,a,4,d,b,5)};function kd(a){ac.call(this,a,3)}z(kd,ac);kd.prototype.r=function(a,b,d){var e=new A(10,0);Yb(this.element,this.Pa,a,b,e,d,9)&496&&Yb(this.element,2,a,1,e,d,5)};function ld(a,b,d){Zc.call(this,a,b,d)}z(ld,Zc);r=ld.prototype;r.Qa=n;r.pb=100;r.na=n;r.Fa=function(){ld.m.Fa.call(this);this.ca=Jb(Wb(this.g()));if(this.anchor)this.xa=Jb(Wb(this.anchor));this.na=this.Qa;var a=J,b=this.pa();a(b.e,"mousemove",this.X,n,this)};r.la=function(){var a=Ac,b=this.pa();a(b.e,"mousemove",this.X,n,this);this.xa=this.ca=this.ua=l;this.na=n;ld.m.la.call(this)};r.sa=function(a){return this.ua?this.ua.contains(a):ld.m.sa.call(this,a)};
function md(a,b){if(a.xa&&a.xa.contains(b)||a.sa(b))return i;var d=a.R;return!!d&&d.sa(b)}r.eb=function(a){this.Y=h;a==this.anchor&&!md(this,this.M)&&!this.f&&(!this.R||!this.R.f)&&(!Za||!(this.M.x==0&&this.M.y==0))&&Qc(this,n)};r.X=function(a){var b=this.k;if(this.ca){var d=Hb(this.pa()),d=new A(a.clientX+d.x,a.clientY+d.y);md(this,d)?b=n:this.na&&(b=Ma(this.ca,d)>=Ma(this.ca,this.M))}if(b){if(fd(this),this.f=l,b=this.R)b.f=l}else cd(this)==3&&dd(this);ld.m.X.call(this,a)};
r.Ba=function(){if(this.f!=this.g()&&(this.na=n,this.f=this.g(),!this.ua&&this.Za))this.ua=this.ca.D().expand(this.Za)};r.Aa=function(){return this.na?this.pb:ld.m.Aa.call(this)};function L(a){return a!=l&&a!==n}function nd(a,b){var d=a[w.call(l,b)];return L(d)?d:(d=a._,L(d)?d:n)}function M(a,b){return Error.call(l,"No protocol method "+a+" defined for type "+w.call(l,b)+": "+b)}function od(a){return Array.prototype.slice.call(a)}function pd(a){return Array.prototype.slice.call(arguments)}function N(a){if(L(L(a)?a.L:a))a=a.L(a);else{var b;var d=N[w.call(l,a)];L(d)?b=d:(d=N._,L(d)?b=d:c(M.call(l,"ICounted.-count",a)));a=b.call(l,a)}return a}
function qd(a,b){var d;if(L(L(a)?a.w:a))d=a.w(a,b);else{var e=qd[w.call(l,a)];L(e)?d=e:(e=qd._,L(e)?d=e:c(M.call(l,"ICollection.-conj",a)));d=d.call(l,a,b)}return d}
var O=function(){return function(a,b,d){switch(arguments.length){case 2:var e;if(L(L(a)?a.da:a))e=a.da(a,b);else{var f=O[w.call(l,a)];L(f)?e=f:(f=O._,L(f)?e=f:c(M.call(l,"IIndexed.-nth",a)));e=e.call(l,a,b)}return e;case 3:return L(L(a)?a.da:a)?e=a.da(a,b,d):(e=O[w.call(l,a)],L(e)?f=e:(e=O._,L(e)?f=e:c(M.call(l,"IIndexed.-nth",a))),e=f.call(l,a,b,d)),e}c("Invalid arity: "+arguments.length)}}(),rd={};
function sd(a){if(L(L(a)?a.T:a))a=a.T(a);else{var b;var d=sd[w.call(l,a)];L(d)?b=d:(d=sd._,L(d)?b=d:c(M.call(l,"ISeq.-first",a)));a=b.call(l,a)}return a}function td(a){if(L(L(a)?a.U:a))a=a.U(a);else{var b;var d=td[w.call(l,a)];L(d)?b=d:(d=td._,L(d)?b=d:c(M.call(l,"ISeq.-rest",a)));a=b.call(l,a)}return a}
var P=function(){return function(a,b,d){switch(arguments.length){case 2:var e;if(L(L(a)?a.S:a))e=a.S(a,b);else{var f=P[w.call(l,a)];L(f)?e=f:(f=P._,L(f)?e=f:c(M.call(l,"ILookup.-lookup",a)));e=e.call(l,a,b)}return e;case 3:return L(L(a)?a.S:a)?e=a.S(a,b,d):(e=P[w.call(l,a)],L(e)?f=e:(e=P._,L(e)?f=e:c(M.call(l,"ILookup.-lookup",a))),e=f.call(l,a,b,d)),e}c("Invalid arity: "+arguments.length)}}();
function ud(a,b,d){if(L(L(a)?a.oa:a))a=a.oa(a,b,d);else{var e;var f=ud[w.call(l,a)];L(f)?e=f:(f=ud._,L(f)?e=f:c(M.call(l,"IAssociative.-assoc",a)));a=e.call(l,a,b,d)}return a}var vd={},wd={},xd={};function yd(a){if(L(L(a)?a.I:a))a=a.d;else{var b;var d=yd[w.call(l,a)];L(d)?b=d:(d=yd._,L(d)?b=d:c(M.call(l,"IMeta.-meta",a)));a=b.call(l,a)}return a}
function zd(a,b){var d;if(L(L(a)?a.J:a))d=a.J(a,b);else{var e=zd[w.call(l,a)];L(e)?d=e:(e=zd._,L(e)?d=e:c(M.call(l,"IWithMeta.-with-meta",a)));d=d.call(l,a,b)}return d}
var Ad=function(){return function(a,b,d){switch(arguments.length){case 2:var e;if(L(L(a)?a.ea:a))e=a.ea(a,b);else{var f=Ad[w.call(l,a)];L(f)?e=f:(f=Ad._,L(f)?e=f:c(M.call(l,"IReduce.-reduce",a)));e=e.call(l,a,b)}return e;case 3:return L(L(a)?a.ea:a)?e=a.ea(a,b,d):(e=Ad[w.call(l,a)],L(e)?f=e:(e=Ad._,L(e)?f=e:c(M.call(l,"IReduce.-reduce",a))),e=f.call(l,a,b,d)),e}c("Invalid arity: "+arguments.length)}}();
function Bd(a,b){var d;if(L(L(a)?a.o:a))d=a.o(a,b);else{var e=Bd[w.call(l,a)];L(e)?d=e:(e=Bd._,L(e)?d=e:c(M.call(l,"IEquiv.-equiv",a)));d=d.call(l,a,b)}return d}function Cd(a){if(L(L(a)?a.z:a))a=a.z(a);else{var b;var d=Cd[w.call(l,a)];L(d)?b=d:(d=Cd._,L(d)?b=d:c(M.call(l,"IHash.-hash",a)));a=b.call(l,a)}return a}function Dd(a){if(L(L(a)?a.C:a))a=a.C(a);else{var b;var d=Dd[w.call(l,a)];L(d)?b=d:(d=Dd._,L(d)?b=d:c(M.call(l,"ISeqable.-seq",a)));a=b.call(l,a)}return a}var Ed={},Fd={};
function Gd(a,b){var d;if(L(L(a)?a.t:a))d=a.t(a,b);else{var e=Gd[w.call(l,a)];L(e)?d=e:(e=Gd._,L(e)?d=e:c(M.call(l,"IPrintable.-pr-seq",a)));d=d.call(l,a,b)}return d}function Hd(a,b){return a===b}function Q(a,b){return Bd.call(l,a,b)}function R(a){return Hd.call(l,a,l)}Cd["null"]=q(0);P["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return l;case 3:return d}c("Invalid arity: "+arguments.length)}}();ud["null"]=function(a,b,d){return Id.call(l,b,d)};
qd["null"]=function(a,b){return S.call(l,b)};Ad["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return b.call(l);case 3:return d}c("Invalid arity: "+arguments.length)}}();Fd["null"]=i;Gd["null"]=function(){return S.call(l,"nil")};N["null"]=q(0);rd["null"]=i;sd["null"]=q(l);td["null"]=function(){return S.call(l)};Bd["null"]=function(a,b){return R.call(l,b)};zd["null"]=q(l);xd["null"]=i;yd["null"]=q(l);
O["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return l;case 3:return d}c("Invalid arity: "+arguments.length)}}();vd["null"]=i;Date.prototype.o=function(a,b){return Hd.call(l,a.toString(),b.toString())};Cd.number=aa();Bd.number=function(a,b){return Hd.call(l,a,b)};Cd["boolean"]=function(a){return a===i?1:0};Cd["function"]=function(a){return ia.call(l,a)};
var Jd=function(){return function(a,b,d,e){switch(arguments.length){case 2:var f;a:if(L(Q.call(l,0,N.call(l,a))))f=b.call(l);else for(var g=O.call(l,a,0),j=1;;)if(L(j<N.call(l,a)))g=b.call(l,g,O.call(l,a,j)),j+=1;else{f=g;break a}return f;case 3:a:{f=d;for(j=0;;)if(L(j<N.call(l,a)))f=b.call(l,f,O.call(l,a,j)),j+=1;else{g=f;break a}}return g;case 4:a:{f=d;for(g=e;;)if(L(g<N.call(l,a)))f=b.call(l,f,O.call(l,a,g)),g+=1;else{j=f;break a}}return j}c("Invalid arity: "+arguments.length)}}();
function Kd(a,b){this.v=a;this.H=b}r=Kd.prototype;r.z=function(a){return Ld.call(l,a)};r.ea=function(){return function(a,b,d){switch(arguments.length){case 2:return Jd.call(l,a,b,this.v[this.H],this.H+1);case 3:return Jd.call(l,a,b,d,this.H)}c("Invalid arity: "+arguments.length)}}();r.w=function(a,b){return T.call(l,b,a)};r.o=function(a,b){return Md.call(l,a,b)};r.V=i;
r.da=function(){return function(a,b,d){switch(arguments.length){case 2:var e=b+this.H;return L(e<this.v.length)?this.v[e]:l;case 3:return e=b+this.H,L(e<this.v.length)?this.v[e]:d}c("Invalid arity: "+arguments.length)}}();r.L=function(){return this.v.length-this.H};r.fa=i;r.T=function(){return this.v[this.H]};r.U=function(){return L(this.H+1<this.v.length)?new Kd(this.v,this.H+1):S.call(l)};r.C=aa();function Nd(a,b){return L(Q.call(l,0,a.length))?l:new Kd(a,b)}
function U(a,b){return Nd.call(l,a,b)}Ad.array=function(){return function(a,b,d){switch(arguments.length){case 2:return Jd.call(l,a,b);case 3:return Jd.call(l,a,b,d)}c("Invalid arity: "+arguments.length)}}();P.array=function(){return function(a,b,d){switch(arguments.length){case 2:return a[b];case 3:return O.call(l,a,b,d)}c("Invalid arity: "+arguments.length)}}();
O.array=function(){return function(a,b,d){switch(arguments.length){case 2:return L(b<a.length)?a[b]:l;case 3:return L(b<a.length)?a[b]:d}c("Invalid arity: "+arguments.length)}}();N.array=function(a){return a.length};Dd.array=function(a){return U.call(l,a,0)};function V(a){return L(a)?Dd.call(l,a):l}function W(a){a=V.call(l,a);return L(a)?sd.call(l,a):l}function X(a){return td.call(l,V.call(l,a))}function Y(a){return L(a)?V.call(l,X.call(l,a)):l}function Od(a){return W.call(l,Y.call(l,a))}
function Pd(a){return Y.call(l,Y.call(l,a))}N._=function(a){for(var a=V.call(l,a),b=0;;)if(L(a))a=Y.call(l,a),b+=1;else return b};Bd._=function(a,b){return Hd.call(l,a,b)};function Qd(a){return L(a)?n:i}
var Rd=function(){var a=l,b=function(){function b(a,d,j){var k=l;v(j)&&(k=U(Array.prototype.slice.call(arguments,2),0));return e.call(this,a,d,k)}function e(b,d,e){for(;;)if(L(e))b=a.call(l,b,d),d=W.call(l,e),e=Y.call(l,e);else return a.call(l,b,d)}b.b=2;b.a=function(a){var b=W(a),d=W(Y(a)),a=X(Y(a));return e.call(this,b,d,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 2:return qd.call(l,a,e);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=
b.a;return a}();function Sd(a){return N.call(l,a)}
var Td=function(){return function(a,b,d){switch(arguments.length){case 2:return P.call(l,a,b);case 3:return P.call(l,a,b,d)}c("Invalid arity: "+arguments.length)}}(),Ud=function(){var a=l,b=function(){function b(a,d,j,k){var m=l;v(k)&&(m=U(Array.prototype.slice.call(arguments,3),0));return e.call(this,a,d,j,m)}function e(b,d,e,k){for(;;)if(b=a.call(l,b,d,e),L(k))d=W.call(l,k),e=Od.call(l,k),k=Pd.call(l,k);else return b}b.b=3;b.a=function(a){var b=W(a),d=W(Y(a)),k=W(Y(Y(a))),a=X(Y(Y(a)));return e.call(this,
b,d,k,a)};return b}(),a=function(a,e,f,g){switch(arguments.length){case 3:return ud.call(l,a,e,f);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=3;a.a=b.a;return a}();function Vd(a,b){return zd.call(l,a,b)}function Wd(a){var b;L(a)?(b=a.A,b=L(b)?Qd.call(l,a.hasOwnProperty("cljs$core$IMeta$")):b):b=a;b=L(b)?i:nd.call(l,xd,a);return L(b)?yd.call(l,a):l}function Xd(a){return Cd.call(l,a)}
function Yd(a){var b;L(a)?(b=a.V,b=L(b)?Qd.call(l,a.hasOwnProperty("cljs$core$ISequential$")):b):b=a;return L(b)?i:nd.call(l,Ed,a)}function Zd(a){if(L(R.call(l,a)))a=n;else{var b;L(a)?(b=a.Oa,b=L(b)?Qd.call(l,a.hasOwnProperty("cljs$core$IMap$")):b):b=a;a=L(b)?i:nd.call(l,vd,a)}return a}function $d(a){var b;L(a)?(b=a.nb,b=L(b)?Qd.call(l,a.hasOwnProperty("cljs$core$IVector$")):b):b=a;return L(b)?i:nd.call(l,wd,a)}
function ae(a){var b=pd.call(l);ob.call(l,a,function(a,e){return b.push(e)});return b}function be(a){return h===a}function ce(a){if(L(R.call(l,a)))a=n;else{var b;L(a)?(b=a.fa,b=L(b)?Qd.call(l,a.hasOwnProperty("cljs$core$ISeq$")):b):b=a;a=L(b)?i:nd.call(l,rd,a)}return a}function de(a){return L(a)?i:n}function ee(a){var b=x.call(l,a);return L(b)?Qd.call(l,function(){var b=Q.call(l,a.charAt(0),"\ufdd0");return L(b)?b:Q.call(l,a.charAt(0),"\ufdd1")}()):b}
function fe(a){var b=x.call(l,a);return L(b)?Q.call(l,a.charAt(0),"\ufdd0"):b}function ge(a){var b=x.call(l,a);return L(b)?Q.call(l,a.charAt(0),"\ufdd1"):b}
var he=function(){return function(a,b,d){switch(arguments.length){case 2:return Ad.call(l,b,a);case 3:return Ad.call(l,d,a,b)}c("Invalid arity: "+arguments.length)}}(),ie=function(){return function(a,b,d){switch(arguments.length){case 2:var e=V.call(l,b);return L(e)?he.call(l,a,W.call(l,e),Y.call(l,e)):a.call(l);case 3:a:for(var f=b,g=V.call(l,d);;)if(L(g))f=a.call(l,f,W.call(l,g)),g=Y.call(l,g);else{e=f;break a}return e}c("Invalid arity: "+arguments.length)}}();
Ad._=function(){return function(a,b,d){switch(arguments.length){case 2:return ie.call(l,b,a);case 3:return ie.call(l,b,d,a)}c("Invalid arity: "+arguments.length)}}();function je(a,b){for(var d=b,e=V.call(l,a);;){var f=e;if(L(L(f)?d>0:f))d-=1,e=Y.call(l,e);else return e}}O._=function(){return function(a,b,d){switch(arguments.length){case 2:var e;var f=je.call(l,a,b);L(f)?e=W.call(l,f):c(Error("Index out of bounds"));return e;case 3:return e=je.call(l,a,b),L(e)?W.call(l,e):d}c("Invalid arity: "+arguments.length)}}();
var ke=function(){var a=l,b=function(){function b(a,d){var j=l;v(d)&&(j=U(Array.prototype.slice.call(arguments,1),0));return e.call(this,a,j)}function e(b,d){return function(b,d){for(;;)if(L(d))var e=b.append(a.call(l,W.call(l,d))),f=Y.call(l,d),b=e,d=f;else return a.call(l,b)}.call(l,new Ka(a.call(l,b)),d)}b.b=1;b.a=function(a){var b=W(a),a=X(a);return e.call(this,b,a)};return b}(),a=function(a,e){switch(arguments.length){case 0:return"";case 1:return L(R.call(l,a))?"":L("\ufdd0'else")?a.toString():
l;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=1;a.a=b.a;return a}(),me=function(){var a=l,b=function(){function a(b,d){var g=l;v(d)&&(g=U(Array.prototype.slice.call(arguments,1),0));return le.call(l,ke,b,g)}a.b=1;a.a=function(a){var b=W(a),a=X(a);return le.call(l,ke,b,a)};return a}(),a=function(a,e){switch(arguments.length){case 0:return"";case 1:return L(ge.call(l,a))?a.substring(2,a.length):L(fe.call(l,a))?ke.call(l,":",a.substring(2,a.length)):L(R.call(l,a))?
"":L("\ufdd0'else")?a.toString():l;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=1;a.a=b.a;return a}(),ne=function(){return function(a,b,d){switch(arguments.length){case 2:return a.substring(b);case 3:return a.substring(b,d)}c("Invalid arity: "+arguments.length)}}();
function Md(a,b){return de.call(l,L(Yd.call(l,b))?function(){for(var d=V.call(l,a),e=V.call(l,b);;)if(L(R.call(l,d)))return R.call(l,e);else if(L(R.call(l,e)))return n;else if(L(Q.call(l,W.call(l,d),W.call(l,e))))d=Y.call(l,d),e=Y.call(l,e);else return L("\ufdd0'else")?n:l}():l)}function oe(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Ld(a){return he.call(l,function(a,d){return oe.call(l,a,Xd.call(l,d))},Xd.call(l,W.call(l,a)),Y.call(l,a))}
function pe(a,b,d,e){this.d=a;this.ia=b;this.$=d;this.u=e}r=pe.prototype;r.z=function(a){return Ld.call(l,a)};r.V=i;r.w=function(a,b){return new pe(this.d,b,a,this.u+1)};r.C=aa();r.L=p("u");r.fa=i;r.T=p("ia");r.U=p("$");r.o=function(a,b){return Md.call(l,a,b)};r.J=function(a,b){return new pe(b,this.ia,this.$,this.u)};r.A=i;r.I=p("d");function qe(a){this.d=a}r=qe.prototype;r.z=function(a){return Ld.call(l,a)};r.V=i;r.w=function(a,b){return new pe(this.d,b,l,1)};r.C=q(l);r.L=q(0);r.fa=i;r.T=q(l);
r.U=q(l);r.o=function(a,b){return Md.call(l,a,b)};r.J=function(a,b){return new qe(b)};r.A=i;r.I=p("d");var re=new qe(l);function se(a){return he.call(l,Rd,re,a)}var S=function(){function a(a){var d=l;v(a)&&(d=U(Array.prototype.slice.call(arguments,0),0));return he.call(l,Rd,re,se.call(l,d))}a.b=0;a.a=function(a){a=V(a);return he.call(l,Rd,re,se.call(l,a))};return a}();function te(a,b,d){this.d=a;this.ia=b;this.$=d}r=te.prototype;r.C=aa();r.z=function(a){return Ld.call(l,a)};
r.o=function(a,b){return Md.call(l,a,b)};r.V=i;r.w=function(a,b){return new te(l,b,a)};r.fa=i;r.T=p("ia");r.U=function(){return L(R.call(l,this.$))?re:this.$};r.A=i;r.I=p("d");r.J=function(a,b){return new te(b,this.ia,this.$)};function T(a,b){return new te(l,a,b)}Ad.string=function(){return function(a,b,d){switch(arguments.length){case 2:return Jd.call(l,a,b);case 3:return Jd.call(l,a,b,d)}c("Invalid arity: "+arguments.length)}}();
P.string=function(){return function(a,b,d){switch(arguments.length){case 2:return O.call(l,a,b);case 3:return O.call(l,a,b,d)}c("Invalid arity: "+arguments.length)}}();O.string=function(){return function(a,b,d){switch(arguments.length){case 2:return L(b<N.call(l,a))?a.charAt(b):l;case 3:return L(b<N.call(l,a))?a.charAt(b):d}c("Invalid arity: "+arguments.length)}}();N.string=function(a){return a.length};Dd.string=function(a){return Nd.call(l,a,0)};Cd.string=function(a){return Ba.call(l,a)};
String.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return Td.call(l,b,this.toString());case 3:return Td.call(l,b,this.toString(),d)}c("Invalid arity: "+arguments.length)}}();String.prototype.apply=function(a,b){return L(Sd.call(l,b)<2)?Td.call(l,b[0],a):Td.call(l,b[0],a,b[1])};function ue(a){var b=a.x;return L(a.Ia)?b:(a.x=b.call(l),a.Ia=i,a.x)}function Z(a,b,d){this.d=a;this.Ia=b;this.x=d}r=Z.prototype;r.C=function(a){return V.call(l,ue.call(l,a))};
r.z=function(a){return Ld.call(l,a)};r.o=function(a,b){return Md.call(l,a,b)};r.V=i;r.w=function(a,b){return T.call(l,b,a)};r.fa=i;r.T=function(a){return W.call(l,ue.call(l,a))};r.U=function(a){return X.call(l,ue.call(l,a))};r.A=i;r.I=p("d");r.J=function(a,b){return new Z(b,this.Ia,this.x)};function ve(a){for(var b=pd.call(l);;)if(L(V.call(l,a)))b.push(W.call(l,a)),a=Y.call(l,a);else return b}
function we(a,b){for(var d=a,e=b,f=0;;){var g;g=e>0;g=L(g)?V.call(l,d):g;if(L(g))d=Y.call(l,d),e-=1,f+=1;else return f}}
var ye=function xe(b){return L(R.call(l,b))?l:L(R.call(l,Y.call(l,b)))?V.call(l,W.call(l,b)):L("\ufdd0'else")?T.call(l,W.call(l,b),xe.call(l,Y.call(l,b))):l},ze=function(){function a(a,b){return new Z(l,n,function(){var d=V.call(l,a);return L(d)?T.call(l,W.call(l,d),e.call(l,X.call(l,d),b)):b})}function b(a){return new Z(l,n,function(){return a})}function d(){return new Z(l,n,q(l))}var e=l,f=function(){function a(d,e,f){var g=l;v(f)&&(g=U(Array.prototype.slice.call(arguments,2),0));return b.call(this,
d,e,g)}function b(a,d,f){return function u(a,b){return new Z(l,n,function(){var d=V.call(l,a);return L(d)?T.call(l,W.call(l,d),u.call(l,X.call(l,d),b)):L(b)?u.call(l,W.call(l,b),Y.call(l,b)):l})}.call(l,e.call(l,a,d),f)}a.b=2;a.a=function(a){var d=W(a),e=W(Y(a)),a=X(Y(a));return b.call(this,d,e,a)};return a}(),e=function(e,j,k){switch(arguments.length){case 0:return d.call(this);case 1:return b.call(this,e);case 2:return a.call(this,e,j);default:return f.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};e.b=2;e.a=f.a;return e}(),Ae=function(){var a=l,b=function(){function a(d,g,j,k,m){var o=l;v(m)&&(o=U(Array.prototype.slice.call(arguments,4),0));return b.call(this,d,g,j,k,o)}function b(a,d,e,k,m){return T.call(l,a,T.call(l,d,T.call(l,e,T.call(l,k,ye.call(l,m)))))}a.b=4;a.a=function(a){var d=W(a),j=W(Y(a)),k=W(Y(Y(a))),m=W(Y(Y(Y(a)))),a=X(Y(Y(Y(a))));return b.call(this,d,j,k,m,a)};return a}(),a=function(a,e,f,g,j){switch(arguments.length){case 1:return V.call(l,a);case 2:return T.call(l,
a,e);case 3:return T.call(l,a,T.call(l,e,f));case 4:return T.call(l,a,T.call(l,e,T.call(l,f,g)));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=4;a.a=b.a;return a}(),le=function(){var a=l,b=function(){function a(d,g,j,k,m,o){var s=l;v(o)&&(s=U(Array.prototype.slice.call(arguments,5),0));return b.call(this,d,g,j,k,m,s)}function b(a,d,e,k,m,o){d=T.call(l,d,T.call(l,e,T.call(l,k,T.call(l,m,ye.call(l,o)))));e=a.b;return L(a.a)?L(we.call(l,d,e)<=e)?a.apply(a,ve.call(l,
d)):a.a(d):a.apply(a,ve.call(l,d))}a.b=5;a.a=function(a){var d=W(a),j=W(Y(a)),k=W(Y(Y(a))),m=W(Y(Y(Y(a)))),o=W(Y(Y(Y(Y(a))))),a=X(Y(Y(Y(Y(a)))));return b.call(this,d,j,k,m,o,a)};return a}(),a=function(a,e,f,g,j,k){switch(arguments.length){case 2:var m=a,o=e,s=m.b;return L(m.a)?L(we.call(l,o,s+1)<=s)?m.apply(m,ve.call(l,o)):m.a(o):m.apply(m,ve.call(l,o));case 3:return m=a,o=Ae.call(l,e,f),s=m.b,L(m.a)?L(we.call(l,o,s)<=s)?m.apply(m,ve.call(l,o)):m.a(o):m.apply(m,ve.call(l,o));case 4:return m=a,o=Ae.call(l,
e,f,g),s=m.b,L(m.a)?L(we.call(l,o,s)<=s)?m.apply(m,ve.call(l,o)):m.a(o):m.apply(m,ve.call(l,o));case 5:return m=a,o=Ae.call(l,e,f,g,j),s=m.b,L(m.a)?L(we.call(l,o,s)<=s)?m.apply(m,ve.call(l,o)):m.a(o):m.apply(m,ve.call(l,o));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=5;a.a=b.a;return a}();function Be(a,b){for(;;)if(L(R.call(l,V.call(l,b))))return i;else if(L(a.call(l,W.call(l,b))))var d=a,e=Y.call(l,b),a=d,b=e;else return L("\ufdd0'else")?n:l}
function Ce(a){return a}
var De=function(){function a(a,b,d,f){return new Z(l,n,function(){var o=V.call(l,b),s=V.call(l,d),u=V.call(l,f);return L(L(o)?L(s)?u:s:o)?T.call(l,a.call(l,W.call(l,o),W.call(l,s),W.call(l,u)),e.call(l,a,X.call(l,o),X.call(l,s),X.call(l,u))):l})}function b(a,b,d){return new Z(l,n,function(){var f=V.call(l,b),o=V.call(l,d);return L(L(f)?o:f)?T.call(l,a.call(l,W.call(l,f),W.call(l,o)),e.call(l,a,X.call(l,f),X.call(l,o))):l})}function d(a,b){return new Z(l,n,function(){var d=V.call(l,b);return L(d)?
T.call(l,a.call(l,W.call(l,d)),e.call(l,a,X.call(l,d))):l})}var e=l,f=function(){function a(d,e,f,g,u){var y=l;v(u)&&(y=U(Array.prototype.slice.call(arguments,4),0));return b.call(this,d,e,f,g,y)}function b(a,d,f,g,j){return e.call(l,function(b){return le.call(l,a,b)},function K(a){return new Z(l,n,function(){var b=e.call(l,V,a);return L(Be.call(l,Ce,b))?T.call(l,e.call(l,W,b),K.call(l,e.call(l,X,b))):l})}.call(l,Rd.call(l,j,g,f,d)))}a.b=4;a.a=function(a){var d=W(a),e=W(Y(a)),f=W(Y(Y(a))),g=W(Y(Y(Y(a)))),
a=X(Y(Y(Y(a))));return b.call(this,d,e,f,g,a)};return a}(),e=function(e,j,k,m,o){switch(arguments.length){case 2:return d.call(this,e,j);case 3:return b.call(this,e,j,k);case 4:return a.call(this,e,j,k,m);default:return f.apply(this,arguments)}c("Invalid arity: "+arguments.length)};e.b=4;e.a=f.a;return e}(),Fe=function Ee(b,d){return new Z(l,n,function(){if(L(b>0)){var e=V.call(l,d);return L(e)?T.call(l,W.call(l,e),Ee.call(l,b-1,X.call(l,e))):l}else return l})};
function Ge(a,b){function d(a,b){for(;;){var d=V.call(l,b),j=a>0;if(L(L(j)?d:j))j=a-1,d=X.call(l,d),a=j,b=d;else return d}}return new Z(l,n,function(){return d.call(l,a,b)})}
var He=function(){function a(a){return new Z(l,n,function(){return T.call(l,a,b.call(l,a))})}var b=l;return b=function(d,e){switch(arguments.length){case 1:return a.call(this,d);case 2:return Fe.call(l,d,b.call(l,e))}c("Invalid arity: "+arguments.length)}}(),Ie=function(){function a(a,d){return new Z(l,n,function(){var g=V.call(l,a),j=V.call(l,d);return L(L(g)?j:g)?T.call(l,W.call(l,g),T.call(l,W.call(l,j),b.call(l,X.call(l,g),X.call(l,j)))):l})}var b=l,d=function(){function a(b,e,k){var m=l;v(k)&&
(m=U(Array.prototype.slice.call(arguments,2),0));return d.call(this,b,e,m)}function d(a,e,f){return new Z(l,n,function(){var d=De.call(l,V,Rd.call(l,f,e,a));return L(Be.call(l,Ce,d))?ze.call(l,De.call(l,W,d),le.call(l,b,De.call(l,X,d))):l})}a.b=2;a.a=function(a){var b=W(a),e=W(Y(a)),a=X(Y(a));return d.call(this,b,e,a)};return a}(),b=function(b,f,g){switch(arguments.length){case 2:return a.call(this,b,f);default:return d.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.b=2;b.a=d.a;return b}();
function Je(a,b){return Ge.call(l,1,Ie.call(l,He.call(l,a),b))}function Ke(a){return function d(a,f){return new Z(l,n,function(){var g=V.call(l,a);return L(g)?T.call(l,W.call(l,g),d.call(l,X.call(l,g),f)):L(V.call(l,f))?d.call(l,W.call(l,f),X.call(l,f)):l})}.call(l,l,a)}
var Le=function(){var a=l,b=function(){function a(b,d,g){var j=l;v(g)&&(j=U(Array.prototype.slice.call(arguments,2),0));return Ke.call(l,le.call(l,De,b,d,j))}a.b=2;a.a=function(a){var b=W(a),d=W(Y(a)),a=X(Y(a));return Ke.call(l,le.call(l,De,b,d,a))};return a}(),a=function(a,e,f){switch(arguments.length){case 2:return Ke.call(l,De.call(l,a,e));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}();function Me(a,b){return he.call(l,qd,a,b)}
var Ne=function(){function a(a,b,g,j){return new Z(l,n,function(){var k=V.call(l,j);if(L(k)){var m=Fe.call(l,a,k);return L(Q.call(l,a,Sd.call(l,m)))?T.call(l,m,d.call(l,a,b,g,Ge.call(l,b,k))):S.call(l,Fe.call(l,a,ze.call(l,m,g)))}else return l})}function b(a,b,g){return new Z(l,n,function(){var j=V.call(l,g);if(L(j)){var k=Fe.call(l,a,j);return L(Q.call(l,a,Sd.call(l,k)))?T.call(l,k,d.call(l,a,b,Ge.call(l,b,j))):l}else return l})}var d=l;return d=function(e,f,g,j){switch(arguments.length){case 2:return d.call(l,
e,e,f);case 3:return b.call(this,e,f,g);case 4:return a.call(this,e,f,g,j)}c("Invalid arity: "+arguments.length)}}();function Oe(a,b){this.d=a;this.n=b}r=Oe.prototype;r.z=function(a){return Ld.call(l,a)};r.S=function(){return function(a,b,d){switch(arguments.length){case 2:return O.call(l,a,b,l);case 3:return O.call(l,a,b,d)}c("Invalid arity: "+arguments.length)}}();r.oa=function(a,b,d){a=od.call(l,this.n);a[b]=d;return new Oe(this.d,a)};r.V=i;
r.w=function(a,b){var d=od.call(l,this.n);d.push(b);return new Oe(this.d,d)};r.ea=function(){return function(a,b,d){switch(arguments.length){case 2:return Jd.call(l,this.n,b);case 3:return Jd.call(l,this.n,b,d)}c("Invalid arity: "+arguments.length)}}();r.C=function(){var a=this;return L(a.n.length>0)?function d(e){return new Z(l,n,function(){return L(e<a.n.length)?T.call(l,a.n[e],d.call(l,e+1)):l})}.call(l,0):l};r.L=function(){return this.n.length};r.nb=i;r.o=function(a,b){return Md.call(l,a,b)};
r.J=function(a,b){return new Oe(b,this.n)};r.A=i;r.I=p("d");r.da=function(){return function(a,b,d){switch(arguments.length){case 2:var e=0<=b;return L(L(e)?b<this.n.length:e)?this.n[b]:l;case 3:return e=0<=b,L(L(e)?b<this.n.length:e)?this.n[b]:d}c("Invalid arity: "+arguments.length)}}();var Pe=new Oe(l,pd.call(l));function Qe(a){return new Oe(l,a)}
Oe.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return P.call(l,this,b);case 3:return P.call(l,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Re(a){return he.call(l,Rd,Pe,a)}var Se=function(){function a(a){var d=l;v(a)&&(d=U(Array.prototype.slice.call(arguments,0),0));return Re.call(l,d)}a.b=0;a.a=function(a){a=V(a);return Re.call(l,a)};return a}();function Te(){}Te.prototype.o=q(n);var Ue=new Te;
function Ve(a,b){return de.call(l,L(Zd.call(l,b))?L(Q.call(l,Sd.call(l,a),Sd.call(l,b)))?Be.call(l,Ce,De.call(l,function(a){return Q.call(l,Td.call(l,b,W.call(l,a),Ue),Od.call(l,a))},a)):l:l)}function We(a,b,d){for(var e=d.length,f=0;;)if(L(f<e))if(L(Q.call(l,b,d[f])))return f;else f+=a;else return l}var Xe=function(){var a=l;return a=function(b,d,e,f){switch(arguments.length){case 2:return a.call(l,b,d,i,n);case 4:var g=x.call(l,b);return L(L(g)?d.hasOwnProperty(b):g)?e:f}c("Invalid arity: "+arguments.length)}}();
function $(a,b,d){this.d=a;this.keys=b;this.aa=d}r=$.prototype;r.z=function(a){return Ld.call(l,a)};r.S=function(){return function(a,b,d){switch(arguments.length){case 2:return P.call(l,a,b,l);case 3:return Xe.call(l,b,this.aa,this.aa[b],d)}c("Invalid arity: "+arguments.length)}}();
r.oa=function(a,b,d){if(L(x.call(l,b))){var a=qb.call(l,this.aa),e=a.hasOwnProperty(b);a[b]=d;return L(e)?new $(this.d,this.keys,a):(d=od.call(l,this.keys),d.push(b),new $(this.d,d,a))}else return Vd.call(l,Me.call(l,Id.call(l,b,d),V.call(l,a)),this.d)};r.w=function(a,b){return L($d.call(l,b))?ud.call(l,a,O.call(l,b,0),O.call(l,b,1)):he.call(l,qd,a,b)};r.C=function(){var a=this;return L(a.keys.length>0)?De.call(l,function(b){return Se.call(l,b,a.aa[b])},a.keys):l};r.L=function(){return this.keys.length};
r.o=function(a,b){return Ve.call(l,a,b)};r.J=function(a,b){return new $(b,this.keys,this.aa)};r.A=i;r.I=p("d");r.Oa=i;pd.call(l);$.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return P.call(l,this,b);case 3:return P.call(l,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Ye(a,b,d){this.d=a;this.u=b;this.P=d}r=Ye.prototype;r.z=function(a){return Ld.call(l,a)};
r.S=function(){return function(a,b,d){switch(arguments.length){case 2:return P.call(l,a,b,l);case 3:var e=this.P[Xd.call(l,b)],f=L(e)?We.call(l,2,b,e):l;return L(f)?e[f+1]:d}c("Invalid arity: "+arguments.length)}}();
r.oa=function(a,b,d){var a=Xd.call(l,b),e=this.P[a];if(L(e)){var e=od.call(l,e),f=qb.call(l,this.P);f[a]=e;a=We.call(l,2,b,e);return L(a)?(e[a+1]=d,new Ye(this.d,this.u,f)):(e.push(b,d),new Ye(this.d,this.u+1,f))}else return e=qb.call(l,this.P),e[a]=pd.call(l,b,d),new Ye(this.d,this.u+1,e)};r.w=function(a,b){return L($d.call(l,b))?ud.call(l,a,O.call(l,b,0),O.call(l,b,1)):he.call(l,qd,a,b)};
r.C=function(){var a=this;if(L(a.u>0)){var b=ae.call(l,a.P);return Le.call(l,function(b){return De.call(l,Re,Ne.call(l,2,a.P[b]))},b)}else return l};r.L=p("u");r.o=function(a,b){return Ve.call(l,a,b)};r.J=function(a,b){return new Ye(b,this.u,this.P)};r.A=i;r.I=p("d");r.Oa=i;var Ze=new Ye(l,0,function(){return{}}.call(l));Ye.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return P.call(l,this,b);case 3:return P.call(l,this,b,d)}c("Invalid arity: "+arguments.length)}}();
var Id=function(){function a(a){var e=l;v(a)&&(e=U(Array.prototype.slice.call(arguments,0),0));return b.call(this,e)}function b(a){for(var a=V.call(l,a),b=Ze;;)if(L(a))var f=Pd.call(l,a),b=Ud.call(l,b,W.call(l,a),Od.call(l,a)),a=f;else return b}a.b=0;a.a=function(a){a=V(a);return b.call(this,a)};return a}();Id.call(l);
function $e(a){if(L(ee.call(l,a)))return a;else{var b;b=fe.call(l,a);b=L(b)?b:ge.call(l,a);if(L(b))return b=a.lastIndexOf("/"),L(b<0)?ne.call(l,a,2):ne.call(l,a,b+1);else if(L("\ufdd0'else"))c(Error(me.call(l,"Doesn't support name: ",a)));else return l}}function af(a){var b;b=fe.call(l,a);b=L(b)?b:ge.call(l,a);if(L(b))return b=a.lastIndexOf("/"),L(b>-1)?ne.call(l,a,2,b):l;else c(Error(me.call(l,"Doesn't support namespace: ",a)))}
function bf(a,b,d,e,f,g){return ze.call(l,Qe([b]),Ke.call(l,Je.call(l,Qe([d]),De.call(l,function(b){return a.call(l,b,f)},g))),Qe([e]))}
var df=function cf(b,d){return L(R.call(l,b))?S.call(l,"nil"):L(be.call(l,b))?S.call(l,"#<undefined>"):L("\ufdd0'else")?ze.call(l,L(function(){var e=Td.call(l,d,"\ufdd0'meta");return L(e)?(L(b)?(e=b.A,e=L(e)?Qd.call(l,b.hasOwnProperty("cljs$core$IMeta$")):e):e=b,e=L(e)?i:nd.call(l,xd,b),L(e)?Wd.call(l,b):e):e}())?ze.call(l,Qe(["^"]),cf.call(l,Wd.call(l,b),d),Qe([" "])):l,L(function(){var d;L(b)?(d=b.B,d=L(d)?Qd.call(l,b.hasOwnProperty("cljs$core$IPrintable$")):d):d=b;return L(d)?i:nd.call(l,Fd,b)}())?
Gd.call(l,b,d):S.call(l,"#<",me.call(l,b),">")):l};Ye.prototype.B=i;Ye.prototype.t=function(a,b){return bf.call(l,function(a){return bf.call(l,df,""," ","",b,a)},"{",", ","}",b,a)};Fd.number=i;Gd.number=function(a){return S.call(l,me.call(l,a))};Kd.prototype.B=i;Kd.prototype.t=function(a,b){return bf.call(l,df,"("," ",")",b,a)};Z.prototype.B=i;Z.prototype.t=function(a,b){return bf.call(l,df,"("," ",")",b,a)};Fd["boolean"]=i;Gd["boolean"]=function(a){return S.call(l,me.call(l,a))};Fd.string=i;
Gd.string=function(a,b){return L(fe.call(l,a))?S.call(l,me.call(l,":",function(){var b=af.call(l,a);return L(b)?me.call(l,b,"/"):l}(),$e.call(l,a))):L(ge.call(l,a))?S.call(l,me.call(l,function(){var b=af.call(l,a);return L(b)?me.call(l,b,"/"):l}(),$e.call(l,a))):L("\ufdd0'else")?S.call(l,L("\ufdd0'readably".call(l,b))?ya.call(l,a):a):l};Oe.prototype.B=i;Oe.prototype.t=function(a,b){return bf.call(l,df,"["," ","]",b,a)};pe.prototype.B=i;
pe.prototype.t=function(a,b){return bf.call(l,df,"("," ",")",b,a)};Fd.array=i;Gd.array=function(a,b){return bf.call(l,df,"#<Array [",", ","]>",b,a)};qe.prototype.B=i;qe.prototype.t=function(){return S.call(l,"()")};te.prototype.B=i;te.prototype.t=function(a,b){return bf.call(l,df,"("," ",")",b,a)};$.prototype.B=i;$.prototype.t=function(a,b){return bf.call(l,function(a){return bf.call(l,df,""," ","",b,a)},"{",", ","}",b,a)};function ef(a,b,d,e){this.state=a;this.d=b;this.zb=d;this.Ab=e}r=ef.prototype;
r.B=i;r.t=function(a,b){return ze.call(l,Qe(["#<Atom: "]),Gd.call(l,this.state,b),">")};r.A=i;r.I=p("d");r.o=function(a,b){return Hd.call(l,a,b)};
(function(){var a=l,b=function(){function a(d,g){var j=l;v(g)&&(j=U(Array.prototype.slice.call(arguments,1),0));return b.call(this,d,j)}function b(a,d){var e=L(ce.call(l,d))?le.call(l,Id,d):d,k=Td.call(l,e,"\ufdd0'validator"),e=Td.call(l,e,"\ufdd0'meta");return new ef(a,e,k,l)}a.b=1;a.a=function(a){var d=W(a),a=X(a);return b.call(this,d,a)};return a}(),a=function(a,e){switch(arguments.length){case 1:return new ef(a,l,l,l);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};
a.b=1;a.a=b.a;return a})().call(l,function(){return new $(l,["\ufdd0'parents","\ufdd0'descendants","\ufdd0'ancestors"],{"\ufdd0'parents":new $(l,[],{}),"\ufdd0'descendants":new $(l,[],{}),"\ufdd0'ancestors":new $(l,[],{})})}.call(l));function ff(a,b){var d=Bb.call(l,"link");zb.call(l,d,(new $(l,["type","rel","href"],{type:"text/css",rel:"stylesheet",href:b})).aa);return Fb.call(l,a,d)}ba("advancedtooltip.prepenvironment",function(){function a(a,b){return me.call(l,a,$e.call(l,b),".css")}var b=wb.call(l,"head").item(0),d=V.call(l,S.call(l,a.call(l,"../css/","\ufdd0'demo"),a.call(l,"css","\ufdd0'tooltip")));if(L(d))for(var e=W.call(l,d);;)if(ff.call(l,b,e),e=Y.call(l,d),L(e))d=e,e=W.call(l,d);else return l;else return l});
ba("advancedtooltip.buildtooltip",function(a){var b=new ld(a);bd(b,me.call(l,"<h2>AdvancedTooltip</h2>","<ul><li>Move cursor towards the tooltip (<em>that's me!</em>) ","and see that it remains open.</li>","<li>Before reaching it start moving the cursor in another ","direction...</li>","<li>Once the cursor reaches the tooltip the cursor tracking is turned ","off and  a 10px 'padding' around it gets added. As long as the cursor ","stays inside the box formed by the tooltip and the padding it remains ",
'open.</li></ul><hr/><div style="text-align: center;">','<button id="btn-nest">Hover me</button>&nbsp;','<button id="btn-close">Close</button></div>'));b.Za=new B(5,5,5,5)||l;b.Qa=i;Tc(b);b.Xa=250;bd(new ld("btn-nest"),"Clicking<br> this<br> button<br> has no effect.");new Zc("btn-close","Closes tooltip");return J(new vb("btn-close"),"click",function(){return Qc(b,n)})});
